// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

package pki

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rsa"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"io"
	"math/big"
)

// TPM 2.0 constants from TPM 2.0 Part 2: Structures
// Reference: https://trustedcomputinggroup.org/resource/tpm-library-specification/
const (
	// TPM_GENERATED_VALUE is the magic value that must appear at the start of
	// all TPM-generated attestation structures. The value 0xff544347 represents
	// the bytes 0xff followed by the ASCII string "TCG" (Trusted Computing Group).
	// This prevents confusion between TPM-generated and user-generated data.
	TPM_GENERATED_VALUE = 0xff544347

	// TPM_ST_ATTEST_CERTIFY indicates that the attestation structure contains
	// certification data (TPMS_CERTIFY_INFO), meaning the TPM is certifying
	// that a specific key exists on the TPM and has certain properties.
	TPM_ST_ATTEST_CERTIFY = 0x8017

	// TPM_ALG_ID values identify cryptographic algorithms used by the TPM
	TPM_ALG_RSA    = 0x0001 // RSA asymmetric algorithm
	TPM_ALG_SHA256 = 0x000B // SHA-256 hash algorithm
	TPM_ALG_NULL   = 0x0010 // NULL algorithm (indicates no algorithm)
	TPM_ALG_RSASSA = 0x0014 // RSASSA signature scheme
	TPM_ALG_RSAPSS = 0x0016 // RSAPSS signature scheme
	TPM_ALG_ECDSA  = 0x0018 // ECDSA signature scheme

	// Additional hash algorithm constants for signature parsing
	TPM_ALG_SHA1   = 0x0004 // SHA-1 hash algorithm
	TPM_ALG_SHA384 = 0x000C // SHA-384 hash algorithm
	TPM_ALG_SHA512 = 0x000D // SHA-512 hash algorithm

	// TPM ECC curve identifiers (TPM 2.0 Part 2, Section 6.4)
	TPM_ECC_NIST_P256 = 0x0003 // NIST P-256 (secp256r1)
	TPM_ECC_NIST_P384 = 0x0004 // NIST P-384 (secp384r1)
	TPM_ECC_NIST_P521 = 0x0005 // NIST P-521 (secp521r1)
)

// TPMS_ATTEST represents the TPM attestation structure as defined in
// TPM 2.0 Part 2, Section 10.12.8. This structure is signed by the TPM
// and provides cryptographic proof of various TPM operations.
//
// For ACME device attestation, this structure proves that a specific key
// exists on the TPM and binds the attestation to the ACME challenge via
// the ExtraData field (which contains the SHA-256 hash of the ACME key authorization).
type TPMS_ATTEST struct {
	// Magic must be TPM_GENERATED_VALUE (0xff544347) to prove this structure
	// was generated by a genuine TPM and not forged by software
	Magic uint32

	// Type identifies the attestation type. For key certification, this is
	// TPM_ST_ATTEST_CERTIFY (0x8017)
	Type uint16

	// QualifiedSigner is the TPM2B_NAME of the key that signed this attestation.
	// In ACME device attestation, this is the Attestation Identity Key (AIK)
	QualifiedSigner []byte

	// ExtraData is application-specific data (TPM2B_DATA) that the TPM includes
	// in the signed attestation. For ACME device attestation, this MUST contain
	// the SHA-256 hash of the key authorization, binding the attestation to the
	// specific ACME challenge
	ExtraData []byte

	// ClockInfo provides TPM clock and reset counter information
	ClockInfo ClockInfo

	// FirmwareVersion is the TPM firmware version number
	FirmwareVersion uint64

	// AttestedCertify contains the certification-specific data when Type is
	// TPM_ST_ATTEST_CERTIFY. This includes the name of the certified key.
	AttestedCertify *TPMS_CERTIFY_INFO
}

// ClockInfo represents TPMS_CLOCK_INFO from TPM 2.0 Part 2, Section 10.11.1
// This provides information about the TPM's internal clock and reset counters
type ClockInfo struct {
	Clock        uint64 // Time in milliseconds since TPM was first powered on
	ResetCount   uint32 // Number of TPM resets since last TPM Clear
	RestartCount uint32 // Number of TPM restarts/resumes since last TPM Reset
	Safe         byte   // 1 if Clock is safe (advanced at expected rate), 0 otherwise
}

// TPMS_CERTIFY_INFO represents the certify-specific attestation data as defined in
// TPM 2.0 Part 2, Section 10.12.3. This structure is part of TPMS_ATTEST when the
// attestation type is TPM_ST_ATTEST_CERTIFY.
//
// It contains the TPM Name of the certified object, which is a cryptographic hash
// of the object's public area. This proves that the attested key has specific
// properties (algorithm, size, attributes, etc.) without revealing the private key.
type TPMS_CERTIFY_INFO struct {
	// Name is the TPM2B_NAME of the certified object. This is computed as:
	// nameAlg || Hash(TPMT_PUBLIC)
	// For ACME device attestation, this must match the hash of the pubArea
	// provided in the attestation statement
	Name []byte

	// QualifiedName is the TPM2B_NAME with the full hierarchy path.
	// This is not typically used in ACME device attestation
	QualifiedName []byte
}

// TPMT_PUBLIC represents the TPM public key structure as defined in
// TPM 2.0 Part 2, Section 12.2.4. This structure describes the public portion
// of a TPM object (typically a key) and is used to verify attestations.
//
// The structure is parsed from the pubArea field in TPM attestation statements
// and its hash (Name) must match the Name in TPMS_CERTIFY_INFO.
type TPMT_PUBLIC struct {
	// Type identifies the key algorithm (e.g., TPM_ALG_RSA, TPM_ALG_ECDSA)
	Type uint16

	// NameAlg is the hash algorithm used to compute the object's Name
	// (typically TPM_ALG_SHA256)
	NameAlg uint16

	// ObjectAttr contains the TPMA_OBJECT attribute flags that define
	// the object's properties (e.g., fixedTPM, fixedParent, sign, decrypt)
	ObjectAttr uint32

	// AuthPolicy is the TPM2B_DIGEST containing the authorization policy
	// for using this object (empty if no policy)
	AuthPolicy []byte

	// Parameters contains the type-specific public key parameters
	// (union selected by Type field)
	Parameters *TPMUPublicParms

	// Unique contains the public key material itself
	// (union selected by Type field)
	Unique *TPMUPublicID
}

// TPMUPublicParms is a union of public key parameters (TPMU_PUBLIC_PARMS).
// Only one field will be populated depending on the key type.
type TPMUPublicParms struct {
	RSADetail *TPMSRSAParms // For RSA keys (Type == TPM_ALG_RSA)
	ECCDetail *TPMSECCParms // For ECC keys (Type == TPM_ALG_ECDSA)
}

// TPMSRSAParms represents RSA key parameters (TPMS_RSA_PARMS) as defined in
// TPM 2.0 Part 2, Section 12.2.3.5
type TPMSRSAParms struct {
	Symmetric uint16 // TPMT_SYM_DEF_OBJECT - symmetric algorithm for key (usually TPM_ALG_NULL)
	Scheme    uint16 // TPMT_RSA_SCHEME - RSA scheme (e.g., TPM_ALG_RSASSA, TPM_ALG_NULL)
	KeyBits   uint16 // Key size in bits (e.g., 2048, 3072, 4096)
	Exponent  uint32 // Public exponent (0 means default of 65537)
}

// TPMSECCParms represents ECC key parameters (TPMS_ECC_PARMS) as defined in
// TPM 2.0 Part 2, Section 12.2.3.6
type TPMSECCParms struct {
	Symmetric uint16 // TPMT_SYM_DEF_OBJECT - symmetric algorithm (usually TPM_ALG_NULL)
	Scheme    uint16 // TPMT_ECC_SCHEME - ECC scheme (e.g., TPM_ALG_ECDSA, TPM_ALG_NULL)
	CurveID   uint16 // TPM_ECC_CURVE - ECC curve identifier (e.g., TPM_ECC_NIST_P256)
	KDF       uint16 // TPMT_KDF_SCHEME - key derivation function (usually TPM_ALG_NULL)
}

// TPMUPublicID is a union of public key unique identifiers (TPMU_PUBLIC_ID).
// This contains the actual public key material. Only one field will be populated
// depending on the key type.
type TPMUPublicID struct {
	RSA []byte     // For RSA keys: the public modulus (n)
	ECC *ECCPoint  // For ECC keys: the public point (x, y)
}

// ECCPoint represents an elliptic curve point with x and y coordinates
type ECCPoint struct {
	X []byte // X coordinate of the ECC point
	Y []byte // Y coordinate of the ECC point
}

// ParseTPMS_ATTEST parses a TPMS_ATTEST structure from its binary representation.
// The input data should be the raw bytes from the certInfo field of a TPM attestation statement.
//
// The binary format follows TPM 2.0 Part 2, Section 10.12.8:
//   - magic (4 bytes, big-endian) - must be TPM_GENERATED_VALUE
//   - type (2 bytes, big-endian) - attestation type
//   - qualifiedSigner (TPM2B_NAME) - 2-byte size + data
//   - extraData (TPM2B_DATA) - 2-byte size + data
//   - clockInfo (17 bytes) - clock, resetCount, restartCount, safe
//   - firmwareVersion (8 bytes)
//   - attested (union based on type) - for CERTIFY: name + qualifiedName
//
// Returns an error if the data is malformed or contains invalid values.
func ParseTPMS_ATTEST(data []byte) (*TPMS_ATTEST, error) {
	buf := bytes.NewReader(data)
	attest := &TPMS_ATTEST{}

	// Read magic (4 bytes)
	if err := binary.Read(buf, binary.BigEndian, &attest.Magic); err != nil {
		return nil, fmt.Errorf("failed to read magic: %w", err)
	}
	if attest.Magic != TPM_GENERATED_VALUE {
		return nil, fmt.Errorf("invalid magic value: got 0x%x, expected 0x%x", attest.Magic, TPM_GENERATED_VALUE)
	}

	// Read type (2 bytes)
	if err := binary.Read(buf, binary.BigEndian, &attest.Type); err != nil {
		return nil, fmt.Errorf("failed to read type: %w", err)
	}
	if attest.Type != TPM_ST_ATTEST_CERTIFY {
		return nil, fmt.Errorf("unsupported attestation type: 0x%x (expected TPM_ST_ATTEST_CERTIFY 0x%x)", attest.Type, TPM_ST_ATTEST_CERTIFY)
	}

	// Read qualifiedSigner (TPM2B_NAME - size prefix + data)
	var err error
	attest.QualifiedSigner, err = readTPM2B(buf)
	if err != nil {
		return nil, fmt.Errorf("failed to read qualifiedSigner: %w", err)
	}

	// Read extraData (TPM2B_DATA - this is what we need!)
	attest.ExtraData, err = readTPM2B(buf)
	if err != nil {
		return nil, fmt.Errorf("failed to read extraData: %w", err)
	}

	// Read clock info
	if err := binary.Read(buf, binary.BigEndian, &attest.ClockInfo.Clock); err != nil {
		return nil, fmt.Errorf("failed to read clock: %w", err)
	}
	if err := binary.Read(buf, binary.BigEndian, &attest.ClockInfo.ResetCount); err != nil {
		return nil, fmt.Errorf("failed to read resetCount: %w", err)
	}
	if err := binary.Read(buf, binary.BigEndian, &attest.ClockInfo.RestartCount); err != nil {
		return nil, fmt.Errorf("failed to read restartCount: %w", err)
	}
	if err := binary.Read(buf, binary.BigEndian, &attest.ClockInfo.Safe); err != nil {
		return nil, fmt.Errorf("failed to read safe: %w", err)
	}

	// Read firmware version
	if err := binary.Read(buf, binary.BigEndian, &attest.FirmwareVersion); err != nil {
		return nil, fmt.Errorf("failed to read firmwareVersion: %w", err)
	}

	// Read attested union (TPMU_ATTEST)
	// For TPM_ST_ATTEST_CERTIFY, this is TPMS_CERTIFY_INFO
	attest.AttestedCertify = &TPMS_CERTIFY_INFO{}
	attest.AttestedCertify.Name, err = readTPM2B(buf)
	if err != nil {
		return nil, fmt.Errorf("failed to read name: %w", err)
	}
	attest.AttestedCertify.QualifiedName, err = readTPM2B(buf)
	if err != nil {
		return nil, fmt.Errorf("failed to read qualifiedName: %w", err)
	}

	return attest, nil
}

// ParseTPMT_PUBLIC parses a TPMT_PUBLIC structure from its binary representation.
// The input data should be the raw bytes from the pubArea field of a TPM attestation statement.
//
// The binary format follows TPM 2.0 Part 2, Section 12.2.4:
//   - type (2 bytes, big-endian) - key algorithm (TPM_ALG_RSA, TPM_ALG_ECDSA, etc.)
//   - nameAlg (2 bytes, big-endian) - hash algorithm for computing Name
//   - objectAttributes (4 bytes, big-endian) - TPMA_OBJECT flags
//   - authPolicy (TPM2B_DIGEST) - 2-byte size + digest data
//   - parameters (union based on type) - algorithm-specific parameters
//   - unique (union based on type) - public key material
//
// The parameters and unique fields are parsed differently depending on the key type.
// Currently supports TPM_ALG_RSA and TPM_ALG_ECDSA.
//
// Returns an error if the data is malformed or contains unsupported key types.
func ParseTPMT_PUBLIC(data []byte) (*TPMT_PUBLIC, error) {
	buf := bytes.NewReader(data)
	pub := &TPMT_PUBLIC{}

	// Read type (2 bytes)
	if err := binary.Read(buf, binary.BigEndian, &pub.Type); err != nil {
		return nil, fmt.Errorf("failed to read type: %w", err)
	}

	// Read nameAlg (2 bytes)
	if err := binary.Read(buf, binary.BigEndian, &pub.NameAlg); err != nil {
		return nil, fmt.Errorf("failed to read nameAlg: %w", err)
	}

	// Read objectAttributes (4 bytes)
	if err := binary.Read(buf, binary.BigEndian, &pub.ObjectAttr); err != nil {
		return nil, fmt.Errorf("failed to read objectAttributes: %w", err)
	}

	// Read authPolicy (TPM2B_DIGEST)
	var err error
	pub.AuthPolicy, err = readTPM2B(buf)
	if err != nil {
		return nil, fmt.Errorf("failed to read authPolicy: %w", err)
	}

	// Read parameters (TPMU_PUBLIC_PARMS - depends on type)
	pub.Parameters = &TPMUPublicParms{}
	switch pub.Type {
	case TPM_ALG_RSA:
		pub.Parameters.RSADetail, err = readTPMSRSAParms(buf)
		if err != nil {
			return nil, fmt.Errorf("failed to read RSA parameters: %w", err)
		}
	case TPM_ALG_ECDSA:
		pub.Parameters.ECCDetail, err = readTPMSECCParms(buf)
		if err != nil {
			return nil, fmt.Errorf("failed to read ECC parameters: %w", err)
		}
	default:
		return nil, fmt.Errorf("unsupported key type: 0x%x", pub.Type)
	}

	// Read unique (TPMU_PUBLIC_ID - depends on type)
	pub.Unique = &TPMUPublicID{}
	switch pub.Type {
	case TPM_ALG_RSA:
		pub.Unique.RSA, err = readTPM2B(buf)
		if err != nil {
			return nil, fmt.Errorf("failed to read RSA modulus: %w", err)
		}
	case TPM_ALG_ECDSA:
		pub.Unique.ECC = &ECCPoint{}
		pub.Unique.ECC.X, err = readTPM2B(buf)
		if err != nil {
			return nil, fmt.Errorf("failed to read ECC X: %w", err)
		}
		pub.Unique.ECC.Y, err = readTPM2B(buf)
		if err != nil {
			return nil, fmt.Errorf("failed to read ECC Y: %w", err)
		}
	}

	return pub, nil
}

// readTPM2B reads a TPM2B_* structure from a reader.
// TPM2B structures are length-prefixed byte arrays used throughout TPM 2.0.
//
// Binary format:
//   - size (2 bytes, big-endian) - length of the data in bytes
//   - data (size bytes) - the actual data
//
// If size is 0, returns nil without reading any data bytes.
// This is the standard TPM format for variable-length byte arrays like TPM2B_NAME,
// TPM2B_DATA, TPM2B_DIGEST, etc.
func readTPM2B(r io.Reader) ([]byte, error) {
	var size uint16
	if err := binary.Read(r, binary.BigEndian, &size); err != nil {
		return nil, err
	}
	if size == 0 {
		return nil, nil
	}
	data := make([]byte, size)
	if _, err := io.ReadFull(r, data); err != nil {
		return nil, err
	}
	return data, nil
}

// readTPMSRSAParms reads TPMS_RSA_PARMS structure from a reader.
// This structure contains RSA-specific key parameters.
//
// Binary format (TPM 2.0 Part 2, Section 12.2.3.5):
//   - symmetric (TPMT_SYM_DEF_OBJECT) - 2 bytes + optional params if not NULL
//   - scheme (TPMT_RSA_SCHEME) - 2 bytes + optional params if not NULL
//   - keyBits (2 bytes) - RSA key size in bits
//   - exponent (4 bytes) - RSA public exponent (0 = default 65537)
//
// Note: The symmetric and scheme fields may have additional parameters
// if they are not TPM_ALG_NULL, which this function handles.
func readTPMSRSAParms(r io.Reader) (*TPMSRSAParms, error) {
	parms := &TPMSRSAParms{}

	// Read symmetric (TPMT_SYM_DEF_OBJECT)
	if err := binary.Read(r, binary.BigEndian, &parms.Symmetric); err != nil {
		return nil, err
	}
	// If symmetric is not TPM_ALG_NULL, there are additional fields
	if parms.Symmetric != TPM_ALG_NULL {
		// Skip symmetric parameters (keyBits + mode)
		var keyBits, mode uint16
		if err := binary.Read(r, binary.BigEndian, &keyBits); err != nil {
			return nil, err
		}
		if err := binary.Read(r, binary.BigEndian, &mode); err != nil {
			return nil, err
		}
	}

	// Read scheme (TPMT_RSA_SCHEME)
	if err := binary.Read(r, binary.BigEndian, &parms.Scheme); err != nil {
		return nil, err
	}
	// If scheme is not TPM_ALG_NULL, there are additional fields
	if parms.Scheme != TPM_ALG_NULL {
		// Skip scheme details (hash algorithm)
		var hashAlg uint16
		if err := binary.Read(r, binary.BigEndian, &hashAlg); err != nil {
			return nil, err
		}
	}

	// Read keyBits
	if err := binary.Read(r, binary.BigEndian, &parms.KeyBits); err != nil {
		return nil, err
	}

	// Read exponent
	if err := binary.Read(r, binary.BigEndian, &parms.Exponent); err != nil {
		return nil, err
	}

	return parms, nil
}

// readTPMSECCParms reads TPMS_ECC_PARMS structure from a reader.
// This structure contains ECC-specific key parameters.
//
// Binary format (TPM 2.0 Part 2, Section 12.2.3.6):
//   - symmetric (TPMT_SYM_DEF_OBJECT) - 2 bytes + optional params if not NULL
//   - scheme (TPMT_ECC_SCHEME) - 2 bytes + optional params if not NULL
//   - curveID (2 bytes) - ECC curve identifier
//   - kdf (TPMT_KDF_SCHEME) - 2 bytes + optional params if not NULL
//
// Note: Similar to RSA parameters, the symmetric, scheme, and kdf fields
// may have additional parameters if they are not TPM_ALG_NULL.
func readTPMSECCParms(r io.Reader) (*TPMSECCParms, error) {
	parms := &TPMSECCParms{}

	// Read symmetric
	if err := binary.Read(r, binary.BigEndian, &parms.Symmetric); err != nil {
		return nil, err
	}
	if parms.Symmetric != TPM_ALG_NULL {
		var keyBits, mode uint16
		if err := binary.Read(r, binary.BigEndian, &keyBits); err != nil {
			return nil, err
		}
		if err := binary.Read(r, binary.BigEndian, &mode); err != nil {
			return nil, err
		}
	}

	// Read scheme
	if err := binary.Read(r, binary.BigEndian, &parms.Scheme); err != nil {
		return nil, err
	}
	if parms.Scheme != TPM_ALG_NULL {
		var hashAlg uint16
		if err := binary.Read(r, binary.BigEndian, &hashAlg); err != nil {
			return nil, err
		}
	}

	// Read curve ID
	if err := binary.Read(r, binary.BigEndian, &parms.CurveID); err != nil {
		return nil, err
	}

	// Read KDF
	if err := binary.Read(r, binary.BigEndian, &parms.KDF); err != nil {
		return nil, err
	}
	if parms.KDF != TPM_ALG_NULL {
		var hashAlg uint16
		if err := binary.Read(r, binary.BigEndian, &hashAlg); err != nil {
			return nil, err
		}
	}

	return parms, nil
}

// ToRSAPublicKey converts a TPMT_PUBLIC structure to Go's standard *rsa.PublicKey.
// This is useful for cryptographic operations using the Go crypto library.
//
// Returns an error if:
//   - The key type is not TPM_ALG_RSA
//   - Required RSA parameters or modulus are missing
//
// The exponent defaults to 65537 if the TPM structure has Exponent=0.
func (pub *TPMT_PUBLIC) ToRSAPublicKey() (*rsa.PublicKey, error) {
	if pub.Type != TPM_ALG_RSA {
		return nil, fmt.Errorf("not an RSA key")
	}
	if pub.Parameters.RSADetail == nil {
		return nil, fmt.Errorf("missing RSA parameters")
	}
	if pub.Unique.RSA == nil {
		return nil, fmt.Errorf("missing RSA modulus")
	}

	// Get exponent (default is 65537)
	exponent := pub.Parameters.RSADetail.Exponent
	if exponent == 0 {
		exponent = 65537
	}

	// Create RSA public key
	n := new(big.Int).SetBytes(pub.Unique.RSA)

	return &rsa.PublicKey{
		N: n,
		E: int(exponent),
	}, nil
}

// ToPublicKey converts a TPMT_PUBLIC structure to Go's crypto.PublicKey interface.
// This handles both RSA and ECC keys.
//
// Returns an error if:
//   - The key type is not supported (only TPM_ALG_RSA and TPM_ALG_ECDSA)
//   - Required parameters or key material are missing
//   - For ECC keys, the curve is not supported
func (pub *TPMT_PUBLIC) ToPublicKey() (crypto.PublicKey, error) {
	switch pub.Type {
	case TPM_ALG_RSA:
		return pub.ToRSAPublicKey()
	case TPM_ALG_ECDSA:
		return pub.ToECDSAPublicKey()
	default:
		return nil, fmt.Errorf("unsupported key type: 0x%x", pub.Type)
	}
}

// ToECDSAPublicKey converts a TPMT_PUBLIC structure to Go's standard *ecdsa.PublicKey.
// This is useful for cryptographic operations using the Go crypto library.
//
// Returns an error if:
//   - The key type is not TPM_ALG_ECDSA
//   - Required ECC parameters or point coordinates are missing
//   - The curve is not supported
func (pub *TPMT_PUBLIC) ToECDSAPublicKey() (*ecdsa.PublicKey, error) {
	if pub.Type != TPM_ALG_ECDSA {
		return nil, fmt.Errorf("not an ECDSA key")
	}
	if pub.Parameters.ECCDetail == nil {
		return nil, fmt.Errorf("missing ECC parameters")
	}
	if pub.Unique.ECC == nil {
		return nil, fmt.Errorf("missing ECC point")
	}

	// Map TPM curve ID to Go elliptic curve
	var curve elliptic.Curve
	switch pub.Parameters.ECCDetail.CurveID {
	case TPM_ECC_NIST_P256:
		curve = elliptic.P256()
	case TPM_ECC_NIST_P384:
		curve = elliptic.P384()
	case TPM_ECC_NIST_P521:
		curve = elliptic.P521()
	default:
		return nil, fmt.Errorf("unsupported ECC curve: 0x%x", pub.Parameters.ECCDetail.CurveID)
	}

	// Parse X and Y coordinates
	x := new(big.Int).SetBytes(pub.Unique.ECC.X)
	y := new(big.Int).SetBytes(pub.Unique.ECC.Y)

	return &ecdsa.PublicKey{
		Curve: curve,
		X:     x,
		Y:     y,
	}, nil
}

// ComputeName computes the TPM Name of a public key object.
//
// The TPM Name is a cryptographic binding between an object and its properties,
// computed as: nameAlg (2 bytes) || Hash(pubArea)
//
// This Name is used throughout TPM operations to ensure integrity. In ACME device
// attestation, the computed Name must match the Name field in TPMS_CERTIFY_INFO
// to prove that the attested key has the expected properties.
//
// Parameters:
//   - pubAreaBytes: the raw binary encoding of the TPMT_PUBLIC structure
//
// Currently only supports TPM_ALG_SHA256 as the name algorithm.
// Returns an error if an unsupported name algorithm is specified.
func (pub *TPMT_PUBLIC) ComputeName(pubAreaBytes []byte) ([]byte, error) {
	// Verify we support this name algorithm
	if pub.NameAlg != TPM_ALG_SHA256 {
		return nil, fmt.Errorf("unsupported name algorithm: 0x%x", pub.NameAlg)
	}

	hasher := sha256.New()
	hasher.Write(pubAreaBytes)
	digest := hasher.Sum(nil)

	// Prepend algorithm identifier
	name := make([]byte, 2+len(digest))
	binary.BigEndian.PutUint16(name[0:2], pub.NameAlg)
	copy(name[2:], digest)

	return name, nil
}

// ParseTPMT_SIGNATURE parses a TPMT_SIGNATURE structure and returns the raw signature
// bytes along with algorithm information.
//
// TPMT_SIGNATURE format (TPM 2.0 Part 2, Section 11.3.4):
//   - sigAlg (2 bytes, big-endian) - TPMI_ALG_SIG_SCHEME
//   - signature (union based on sigAlg):
//   - For RSASSA/RSAPSS: TPMS_SIGNATURE_RSA (hashAlg + TPM2B_PUBLIC_KEY_RSA)
//   - For ECDSA: TPMS_SIGNATURE_ECC (hashAlg + TPM2B for r + TPM2B for s)
//
// The returned sigBytes are suitable for use with Go's crypto verification functions:
//   - For RSA: raw signature bytes
//   - For ECDSA: r || s concatenated (each padded to curve size)
//
// Returns:
//   - sigBytes: the raw signature suitable for Go crypto verification
//   - algID: the signature algorithm (TPM_ALG_RSASSA, TPM_ALG_RSAPSS, TPM_ALG_ECDSA)
//   - hashAlg: the hash algorithm used (TPM_ALG_SHA256, etc.)
//   - err: error if parsing fails
func ParseTPMT_SIGNATURE(data []byte) (sigBytes []byte, algID uint16, hashAlg uint16, err error) {
	if len(data) < 2 {
		return nil, 0, 0, fmt.Errorf("TPMT_SIGNATURE too short: need at least 2 bytes for algorithm ID")
	}

	buf := bytes.NewReader(data)

	// Read signature algorithm (2 bytes)
	if err := binary.Read(buf, binary.BigEndian, &algID); err != nil {
		return nil, 0, 0, fmt.Errorf("failed to read sigAlg: %w", err)
	}

	switch algID {
	case TPM_ALG_RSASSA, TPM_ALG_RSAPSS:
		// TPMS_SIGNATURE_RSA format:
		//   - hash (2 bytes) - TPMI_ALG_HASH
		//   - sig (TPM2B_PUBLIC_KEY_RSA) - size prefix + signature bytes
		if err := binary.Read(buf, binary.BigEndian, &hashAlg); err != nil {
			return nil, 0, 0, fmt.Errorf("failed to read RSA hash algorithm: %w", err)
		}

		sigBytes, err = readTPM2B(buf)
		if err != nil {
			return nil, 0, 0, fmt.Errorf("failed to read RSA signature: %w", err)
		}
		return sigBytes, algID, hashAlg, nil

	case TPM_ALG_ECDSA:
		// TPMS_SIGNATURE_ECC format:
		//   - hash (2 bytes) - TPMI_ALG_HASH
		//   - signatureR (TPM2B_ECC_PARAMETER) - size prefix + r bytes
		//   - signatureS (TPM2B_ECC_PARAMETER) - size prefix + s bytes
		if err := binary.Read(buf, binary.BigEndian, &hashAlg); err != nil {
			return nil, 0, 0, fmt.Errorf("failed to read ECDSA hash algorithm: %w", err)
		}

		r, err := readTPM2B(buf)
		if err != nil {
			return nil, 0, 0, fmt.Errorf("failed to read ECDSA r: %w", err)
		}
		s, err := readTPM2B(buf)
		if err != nil {
			return nil, 0, 0, fmt.Errorf("failed to read ECDSA s: %w", err)
		}

		// Concatenate r || s for Go's crypto/ecdsa verification
		// Note: Go's ecdsa.Verify expects r and s as big.Int, but for
		// compatibility with other verification paths, we return r||s
		sigBytes = append(r, s...)
		return sigBytes, algID, hashAlg, nil

	case TPM_ALG_NULL:
		return nil, algID, 0, fmt.Errorf("TPMT_SIGNATURE has NULL algorithm (no signature)")

	default:
		return nil, 0, 0, fmt.Errorf("unsupported signature algorithm: 0x%04x", algID)
	}
}

// TPMHashAlgToGo converts a TPM hash algorithm identifier to a Go crypto.Hash.
// Returns the crypto.Hash value and whether the algorithm is supported.
//
// Supported algorithms:
//   - TPM_ALG_SHA1 (0x0004) -> crypto.SHA1
//   - TPM_ALG_SHA256 (0x000B) -> crypto.SHA256
//   - TPM_ALG_SHA384 (0x000C) -> crypto.SHA384
//   - TPM_ALG_SHA512 (0x000D) -> crypto.SHA512
func TPMHashAlgToGo(tpmAlg uint16) (hashAlg int, supported bool) {
	switch tpmAlg {
	case TPM_ALG_SHA1:
		return 3, true // crypto.SHA1 = 3
	case TPM_ALG_SHA256:
		return 5, true // crypto.SHA256 = 5
	case TPM_ALG_SHA384:
		return 6, true // crypto.SHA384 = 6
	case TPM_ALG_SHA512:
		return 7, true // crypto.SHA512 = 7
	default:
		return 0, false
	}
}
