// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: certservice.proto

package certservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CertificateServiceClient is the client API for CertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateServiceClient interface {
	// RequestCertificate initiates a certificate request and returns the device attestation challenge
	RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	// SubmitAttestation submits the TPM attestation response for validation
	SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error)
	// GetCertificate retrieves the issued certificate if ready
	GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	// EnrollTPM enrolls a TPM device by configuring its root CA and identifier
	// WARNING: This is a PoC-only endpoint. In production, enrollment MUST be
	// performed by administrators through secure out-of-band channels, NOT by clients.
	EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
}

type certificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateServiceClient(cc grpc.ClientConnInterface) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, "/certservice.CertificateService/RequestCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error) {
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, "/certservice.CertificateService/SubmitAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, "/certservice.CertificateService/GetCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, "/certservice.CertificateService/EnrollTPM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateServiceServer is the server API for CertificateService service.
// All implementations should embed UnimplementedCertificateServiceServer
// for forward compatibility
type CertificateServiceServer interface {
	// RequestCertificate initiates a certificate request and returns the device attestation challenge
	RequestCertificate(context.Context, *CertRequest) (*CertResponse, error)
	// SubmitAttestation submits the TPM attestation response for validation
	SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error)
	// GetCertificate retrieves the issued certificate if ready
	GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error)
	// EnrollTPM enrolls a TPM device by configuring its root CA and identifier
	// WARNING: This is a PoC-only endpoint. In production, enrollment MUST be
	// performed by administrators through secure out-of-band channels, NOT by clients.
	EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error)
}

// UnimplementedCertificateServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCertificateServiceServer struct {
}

func (UnimplementedCertificateServiceServer) RequestCertificate(context.Context, *CertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAttestation not implemented")
}
func (UnimplementedCertificateServiceServer) GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollTPM not implemented")
}

// UnsafeCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateServiceServer will
// result in compilation errors.
type UnsafeCertificateServiceServer interface {
	mustEmbedUnimplementedCertificateServiceServer()
}

func RegisterCertificateServiceServer(s grpc.ServiceRegistrar, srv CertificateServiceServer) {
	s.RegisterService(&CertificateService_ServiceDesc, srv)
}

func _CertificateService_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certservice.CertificateService/RequestCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certservice.CertificateService/SubmitAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, req.(*AttestationSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certservice.CertificateService/GetCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).GetCertificate(ctx, req.(*GetCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_EnrollTPM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TPMEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/certservice.CertificateService/EnrollTPM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, req.(*TPMEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateService_ServiceDesc is the grpc.ServiceDesc for CertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certservice.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCertificate",
			Handler:    _CertificateService_RequestCertificate_Handler,
		},
		{
			MethodName: "SubmitAttestation",
			Handler:    _CertificateService_SubmitAttestation_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _CertificateService_GetCertificate_Handler,
		},
		{
			MethodName: "EnrollTPM",
			Handler:    _CertificateService_EnrollTPM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "certservice.proto",
}
