
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: certservice.proto

package certservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertificateService_RequestCertificate_FullMethodName = "/certservice.CertificateService/RequestCertificate"
	CertificateService_SubmitAttestation_FullMethodName  = "/certservice.CertificateService/SubmitAttestation"
	CertificateService_GetCertificate_FullMethodName     = "/certservice.CertificateService/GetCertificate"
	CertificateService_EnrollTPM_FullMethodName          = "/certservice.CertificateService/EnrollTPM"
	CertificateService_ProvisionAIK_FullMethodName       = "/certservice.CertificateService/ProvisionAIK"
)

// CertificateServiceClient is the client API for CertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CertificateService provides certificate issuance with TPM device attestation
type CertificateServiceClient interface {
	// RequestCertificate initiates a certificate request and returns the device attestation challenge
	RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	// SubmitAttestation submits the TPM attestation response for validation
	SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error)
	// GetCertificate retrieves the issued certificate if ready
	GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	// EnrollTPM enrolls a TPM device by configuring its root CA and identifier
	// WARNING: This is a PoC-only endpoint. In production, enrollment MUST be
	// performed by administrators through secure out-of-band channels, NOT by clients.
	EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	// ProvisionAIK issues an IAK certificate for a TPM attestation key (Phase 2 fallback)
	// This endpoint acts as a Privacy CA, issuing IAK certificates for TPMs that lack
	// manufacturer-provisioned IAK certificates. The AK is created by the client using
	// go-attestation NewAK(), and OpenBao signs it after validating the enrolled EK.
	ProvisionAIK(ctx context.Context, in *ProvisionAIKRequest, opts ...grpc.CallOption) (*ProvisionAIKResponse, error)
}

type certificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateServiceClient(cc grpc.ClientConnInterface) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_RequestCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_SubmitAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, CertificateService_EnrollTPM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) ProvisionAIK(ctx context.Context, in *ProvisionAIKRequest, opts ...grpc.CallOption) (*ProvisionAIKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionAIKResponse)
	err := c.cc.Invoke(ctx, CertificateService_ProvisionAIK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateServiceServer is the server API for CertificateService service.
// All implementations must embed UnimplementedCertificateServiceServer
// for forward compatibility.
//
// CertificateService provides certificate issuance with TPM device attestation
type CertificateServiceServer interface {
	// RequestCertificate initiates a certificate request and returns the device attestation challenge
	RequestCertificate(context.Context, *CertRequest) (*CertResponse, error)
	// SubmitAttestation submits the TPM attestation response for validation
	SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error)
	// GetCertificate retrieves the issued certificate if ready
	GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error)
	// EnrollTPM enrolls a TPM device by configuring its root CA and identifier
	// WARNING: This is a PoC-only endpoint. In production, enrollment MUST be
	// performed by administrators through secure out-of-band channels, NOT by clients.
	EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error)
	// ProvisionAIK issues an IAK certificate for a TPM attestation key (Phase 2 fallback)
	// This endpoint acts as a Privacy CA, issuing IAK certificates for TPMs that lack
	// manufacturer-provisioned IAK certificates. The AK is created by the client using
	// go-attestation NewAK(), and OpenBao signs it after validating the enrolled EK.
	ProvisionAIK(context.Context, *ProvisionAIKRequest) (*ProvisionAIKResponse, error)
	mustEmbedUnimplementedCertificateServiceServer()
}

// UnimplementedCertificateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificateServiceServer struct{}

func (UnimplementedCertificateServiceServer) RequestCertificate(context.Context, *CertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAttestation not implemented")
}
func (UnimplementedCertificateServiceServer) GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollTPM not implemented")
}
func (UnimplementedCertificateServiceServer) ProvisionAIK(context.Context, *ProvisionAIKRequest) (*ProvisionAIKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionAIK not implemented")
}
func (UnimplementedCertificateServiceServer) mustEmbedUnimplementedCertificateServiceServer() {}
func (UnimplementedCertificateServiceServer) testEmbeddedByValue()                            {}

// UnsafeCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateServiceServer will
// result in compilation errors.
type UnsafeCertificateServiceServer interface {
	mustEmbedUnimplementedCertificateServiceServer()
}

func RegisterCertificateServiceServer(s grpc.ServiceRegistrar, srv CertificateServiceServer) {
	// If the following call pancis, it indicates UnimplementedCertificateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertificateService_ServiceDesc, srv)
}

func _CertificateService_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_RequestCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_SubmitAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, req.(*AttestationSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).GetCertificate(ctx, req.(*GetCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_EnrollTPM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TPMEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_EnrollTPM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, req.(*TPMEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_ProvisionAIK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionAIKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).ProvisionAIK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_ProvisionAIK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).ProvisionAIK(ctx, req.(*ProvisionAIKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateService_ServiceDesc is the grpc.ServiceDesc for CertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certservice.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCertificate",
			Handler:    _CertificateService_RequestCertificate_Handler,
		},
		{
			MethodName: "SubmitAttestation",
			Handler:    _CertificateService_SubmitAttestation_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _CertificateService_GetCertificate_Handler,
		},
		{
			MethodName: "EnrollTPM",
			Handler:    _CertificateService_EnrollTPM_Handler,
		},
		{
			MethodName: "ProvisionAIK",
			Handler:    _CertificateService_ProvisionAIK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "certservice.proto",
}
