// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/certservice.proto

package certservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CertRequest contains the certificate signing request for IPsec VPN
type CertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common name for the certificate (e.g., "vpn-client-12345")
	CommonName string `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	// Subject Alternative Names - IP addresses
	SanIps []string `protobuf:"bytes,2,rep,name=san_ips,json=sanIps,proto3" json:"san_ips,omitempty"`
	// Subject Alternative Names - DNS names
	SanDns []string `protobuf:"bytes,3,rep,name=san_dns,json=sanDns,proto3" json:"san_dns,omitempty"`
	// PEM-encoded Certificate Signing Request
	CsrPem string `protobuf:"bytes,4,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	// Permanent identifier from TPM (serial number or device ID)
	PermanentIdentifier string `protobuf:"bytes,5,opt,name=permanent_identifier,json=permanentIdentifier,proto3" json:"permanent_identifier,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CertRequest) Reset() {
	*x = CertRequest{}
	mi := &file_proto_certservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRequest) ProtoMessage() {}

func (x *CertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRequest.ProtoReflect.Descriptor instead.
func (*CertRequest) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{0}
}

func (x *CertRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CertRequest) GetSanIps() []string {
	if x != nil {
		return x.SanIps
	}
	return nil
}

func (x *CertRequest) GetSanDns() []string {
	if x != nil {
		return x.SanDns
	}
	return nil
}

func (x *CertRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *CertRequest) GetPermanentIdentifier() string {
	if x != nil {
		return x.PermanentIdentifier
	}
	return ""
}

// AttestationSubmit contains the TPM attestation object
type AttestationSubmit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID from the initial certificate request
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Authorization URL for the challenge
	AuthorizationUrl string `protobuf:"bytes,2,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// Challenge URL to submit attestation to
	ChallengeUrl string `protobuf:"bytes,3,opt,name=challenge_url,json=challengeUrl,proto3" json:"challenge_url,omitempty"`
	// Base64url-encoded CBOR attestation object
	// Format: {fmt: "tpm", attStmt: {ver, alg, x5c, sig, certInfo, pubArea}}
	AttestationObject string `protobuf:"bytes,4,opt,name=attestation_object,json=attestationObject,proto3" json:"attestation_object,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttestationSubmit) Reset() {
	*x = AttestationSubmit{}
	mi := &file_proto_certservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationSubmit) ProtoMessage() {}

func (x *AttestationSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationSubmit.ProtoReflect.Descriptor instead.
func (*AttestationSubmit) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{1}
}

func (x *AttestationSubmit) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AttestationSubmit) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *AttestationSubmit) GetChallengeUrl() string {
	if x != nil {
		return x.ChallengeUrl
	}
	return ""
}

func (x *AttestationSubmit) GetAttestationObject() string {
	if x != nil {
		return x.AttestationObject
	}
	return ""
}

// GetCertRequest requests the certificate for a finalized order
type GetCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Order ID to retrieve certificate for
	OrderId       string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertRequest) Reset() {
	*x = GetCertRequest{}
	mi := &file_proto_certservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertRequest) ProtoMessage() {}

func (x *GetCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertRequest.ProtoReflect.Descriptor instead.
func (*GetCertRequest) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetCertRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// CertResponse contains the response for certificate operations
type CertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the request: "pending", "ready", "valid", "invalid", "error"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Order ID for tracking the certificate request
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Authorization URL containing the challenge
	AuthorizationUrl string `protobuf:"bytes,3,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	// Challenge URL for device-attest-01
	ChallengeUrl string `protobuf:"bytes,4,opt,name=challenge_url,json=challengeUrl,proto3" json:"challenge_url,omitempty"`
	// Challenge token for building key authorization
	ChallengeToken string `protobuf:"bytes,5,opt,name=challenge_token,json=challengeToken,proto3" json:"challenge_token,omitempty"`
	// Account thumbprint for key authorization (JWK thumbprint)
	AccountThumbprint string `protobuf:"bytes,6,opt,name=account_thumbprint,json=accountThumbprint,proto3" json:"account_thumbprint,omitempty"`
	// PEM-encoded certificate if status is "valid"
	CertificatePem string `protobuf:"bytes,7,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// Certificate chain (intermediate + root) in PEM format
	ChainPem []string `protobuf:"bytes,8,rep,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	// Error message if status is "error"
	Error string `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	// Additional information for debugging
	Details       string `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertResponse) Reset() {
	*x = CertResponse{}
	mi := &file_proto_certservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertResponse) ProtoMessage() {}

func (x *CertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertResponse.ProtoReflect.Descriptor instead.
func (*CertResponse) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{3}
}

func (x *CertResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CertResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CertResponse) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *CertResponse) GetChallengeUrl() string {
	if x != nil {
		return x.ChallengeUrl
	}
	return ""
}

func (x *CertResponse) GetChallengeToken() string {
	if x != nil {
		return x.ChallengeToken
	}
	return ""
}

func (x *CertResponse) GetAccountThumbprint() string {
	if x != nil {
		return x.AccountThumbprint
	}
	return ""
}

func (x *CertResponse) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *CertResponse) GetChainPem() []string {
	if x != nil {
		return x.ChainPem
	}
	return nil
}

func (x *CertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CertResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// TPMEnrollmentRequest contains TPM enrollment data sent by the client
// WARNING: In production, this data MUST be provided by administrators through
// secure out-of-band channels. This PoC allows clients to send it for demonstration
// purposes only.
type TPMEnrollmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TPM permanent identifier to allowlist
	PermanentIdentifier string `protobuf:"bytes,1,opt,name=permanent_identifier,json=permanentIdentifier,proto3" json:"permanent_identifier,omitempty"`
	// PEM-encoded TPM EK root CA certificate
	// This is the manufacturer's root certificate that signs the EK certificate chain
	EkRootCaPem string `protobuf:"bytes,2,opt,name=ek_root_ca_pem,json=ekRootCaPem,proto3" json:"ek_root_ca_pem,omitempty"`
	// Name/identifier for the EK root CA (e.g., "intel", "infineon")
	EkRootCaName string `protobuf:"bytes,3,opt,name=ek_root_ca_name,json=ekRootCaName,proto3" json:"ek_root_ca_name,omitempty"`
	// Optional: Description of the TPM device
	DeviceDescription string `protobuf:"bytes,4,opt,name=device_description,json=deviceDescription,proto3" json:"device_description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TPMEnrollmentRequest) Reset() {
	*x = TPMEnrollmentRequest{}
	mi := &file_proto_certservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPMEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPMEnrollmentRequest) ProtoMessage() {}

func (x *TPMEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPMEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*TPMEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{4}
}

func (x *TPMEnrollmentRequest) GetPermanentIdentifier() string {
	if x != nil {
		return x.PermanentIdentifier
	}
	return ""
}

func (x *TPMEnrollmentRequest) GetEkRootCaPem() string {
	if x != nil {
		return x.EkRootCaPem
	}
	return ""
}

func (x *TPMEnrollmentRequest) GetEkRootCaName() string {
	if x != nil {
		return x.EkRootCaName
	}
	return ""
}

func (x *TPMEnrollmentRequest) GetDeviceDescription() string {
	if x != nil {
		return x.DeviceDescription
	}
	return ""
}

// EnrollmentResponse contains the result of TPM enrollment
type EnrollmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status: "success" or "error"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Error message if status is "error"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Confirmation details
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// The enrolled permanent identifier
	PermanentIdentifier string `protobuf:"bytes,4,opt,name=permanent_identifier,json=permanentIdentifier,proto3" json:"permanent_identifier,omitempty"`
	// The enrolled EK root CA name
	EkRootCaName  string `protobuf:"bytes,5,opt,name=ek_root_ca_name,json=ekRootCaName,proto3" json:"ek_root_ca_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_proto_certservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnrollmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnrollmentResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *EnrollmentResponse) GetPermanentIdentifier() string {
	if x != nil {
		return x.PermanentIdentifier
	}
	return ""
}

func (x *EnrollmentResponse) GetEkRootCaName() string {
	if x != nil {
		return x.EkRootCaName
	}
	return ""
}

// ProvisionAIKRequest requests an IAK certificate for a new attestation key
// This is used in AK mode when TPM lacks manufacturer-provisioned IAK
type ProvisionAIKRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TPM permanent identifier (must be already enrolled)
	PermanentIdentifier string `protobuf:"bytes,1,opt,name=permanent_identifier,json=permanentIdentifier,proto3" json:"permanent_identifier,omitempty"`
	// PEM-encoded Certificate Signing Request for the AK
	// The CSR must be created by the client using the AK private key in the TPM
	// This ensures the issued certificate contains the AK public key from the TPM
	AkCsrPem string `protobuf:"bytes,2,opt,name=ak_csr_pem,json=akCsrPem,proto3" json:"ak_csr_pem,omitempty"`
	// PEM-encoded EK certificate for validation
	// Must match the enrolled permanent_identifier
	EkCertificatePem string `protobuf:"bytes,3,opt,name=ek_certificate_pem,json=ekCertificatePem,proto3" json:"ek_certificate_pem,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionAIKRequest) Reset() {
	*x = ProvisionAIKRequest{}
	mi := &file_proto_certservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionAIKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionAIKRequest) ProtoMessage() {}

func (x *ProvisionAIKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionAIKRequest.ProtoReflect.Descriptor instead.
func (*ProvisionAIKRequest) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisionAIKRequest) GetPermanentIdentifier() string {
	if x != nil {
		return x.PermanentIdentifier
	}
	return ""
}

func (x *ProvisionAIKRequest) GetAkCsrPem() string {
	if x != nil {
		return x.AkCsrPem
	}
	return ""
}

func (x *ProvisionAIKRequest) GetEkCertificatePem() string {
	if x != nil {
		return x.EkCertificatePem
	}
	return ""
}

// ProvisionAIKResponse contains the OpenBao-issued IAK certificate
type ProvisionAIKResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status: "success" or "error"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Error message if status is "error"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// PEM-encoded AIK certificate signed by OpenBao /pki-ak CA
	// This certificate can be used in TPM attestation (x5c field)
	IakCertificatePem string `protobuf:"bytes,3,opt,name=iak_certificate_pem,json=iakCertificatePem,proto3" json:"iak_certificate_pem,omitempty"`
	// PEM-encoded OpenBao /pki-ak root CA certificate
	// For building the certificate chain
	IakRootCaPem string `protobuf:"bytes,4,opt,name=iak_root_ca_pem,json=iakRootCaPem,proto3" json:"iak_root_ca_pem,omitempty"`
	// Certificate validity period
	NotBefore     string `protobuf:"bytes,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      string `protobuf:"bytes,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionAIKResponse) Reset() {
	*x = ProvisionAIKResponse{}
	mi := &file_proto_certservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionAIKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionAIKResponse) ProtoMessage() {}

func (x *ProvisionAIKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_certservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionAIKResponse.ProtoReflect.Descriptor instead.
func (*ProvisionAIKResponse) Descriptor() ([]byte, []int) {
	return file_proto_certservice_proto_rawDescGZIP(), []int{7}
}

func (x *ProvisionAIKResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionAIKResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProvisionAIKResponse) GetIakCertificatePem() string {
	if x != nil {
		return x.IakCertificatePem
	}
	return ""
}

func (x *ProvisionAIKResponse) GetIakRootCaPem() string {
	if x != nil {
		return x.IakRootCaPem
	}
	return ""
}

func (x *ProvisionAIKResponse) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *ProvisionAIKResponse) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

var File_proto_certservice_proto protoreflect.FileDescriptor

const file_proto_certservice_proto_rawDesc = "" +
	"\n" +
	"\x17proto/certservice.proto\x12\vcertservice\"\xac\x01\n" +
	"\vCertRequest\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x17\n" +
	"\asan_ips\x18\x02 \x03(\tR\x06sanIps\x12\x17\n" +
	"\asan_dns\x18\x03 \x03(\tR\x06sanDns\x12\x17\n" +
	"\acsr_pem\x18\x04 \x01(\tR\x06csrPem\x121\n" +
	"\x14permanent_identifier\x18\x05 \x01(\tR\x13permanentIdentifier\"\xaf\x01\n" +
	"\x11AttestationSubmit\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12+\n" +
	"\x11authorization_url\x18\x02 \x01(\tR\x10authorizationUrl\x12#\n" +
	"\rchallenge_url\x18\x03 \x01(\tR\fchallengeUrl\x12-\n" +
	"\x12attestation_object\x18\x04 \x01(\tR\x11attestationObject\"+\n" +
	"\x0eGetCertRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xe1\x02\n" +
	"\fCertResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12+\n" +
	"\x11authorization_url\x18\x03 \x01(\tR\x10authorizationUrl\x12#\n" +
	"\rchallenge_url\x18\x04 \x01(\tR\fchallengeUrl\x12'\n" +
	"\x0fchallenge_token\x18\x05 \x01(\tR\x0echallengeToken\x12-\n" +
	"\x12account_thumbprint\x18\x06 \x01(\tR\x11accountThumbprint\x12'\n" +
	"\x0fcertificate_pem\x18\a \x01(\tR\x0ecertificatePem\x12\x1b\n" +
	"\tchain_pem\x18\b \x03(\tR\bchainPem\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x18\n" +
	"\adetails\x18\n" +
	" \x01(\tR\adetails\"\xc4\x01\n" +
	"\x14TPMEnrollmentRequest\x121\n" +
	"\x14permanent_identifier\x18\x01 \x01(\tR\x13permanentIdentifier\x12#\n" +
	"\x0eek_root_ca_pem\x18\x02 \x01(\tR\vekRootCaPem\x12%\n" +
	"\x0fek_root_ca_name\x18\x03 \x01(\tR\fekRootCaName\x12-\n" +
	"\x12device_description\x18\x04 \x01(\tR\x11deviceDescription\"\xb6\x01\n" +
	"\x12EnrollmentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x121\n" +
	"\x14permanent_identifier\x18\x04 \x01(\tR\x13permanentIdentifier\x12%\n" +
	"\x0fek_root_ca_name\x18\x05 \x01(\tR\fekRootCaName\"\x94\x01\n" +
	"\x13ProvisionAIKRequest\x121\n" +
	"\x14permanent_identifier\x18\x01 \x01(\tR\x13permanentIdentifier\x12\x1c\n" +
	"\n" +
	"ak_csr_pem\x18\x02 \x01(\tR\bakCsrPem\x12,\n" +
	"\x12ek_certificate_pem\x18\x03 \x01(\tR\x10ekCertificatePem\"\xd7\x01\n" +
	"\x14ProvisionAIKResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x13iak_certificate_pem\x18\x03 \x01(\tR\x11iakCertificatePem\x12%\n" +
	"\x0fiak_root_ca_pem\x18\x04 \x01(\tR\fiakRootCaPem\x12\x1d\n" +
	"\n" +
	"not_before\x18\x05 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x06 \x01(\tR\bnotAfter2\x9f\x03\n" +
	"\x12CertificateService\x12I\n" +
	"\x12RequestCertificate\x12\x18.certservice.CertRequest\x1a\x19.certservice.CertResponse\x12N\n" +
	"\x11SubmitAttestation\x12\x1e.certservice.AttestationSubmit\x1a\x19.certservice.CertResponse\x12H\n" +
	"\x0eGetCertificate\x12\x1b.certservice.GetCertRequest\x1a\x19.certservice.CertResponse\x12O\n" +
	"\tEnrollTPM\x12!.certservice.TPMEnrollmentRequest\x1a\x1f.certservice.EnrollmentResponse\x12S\n" +
	"\fProvisionAIK\x12 .certservice.ProvisionAIKRequest\x1a!.certservice.ProvisionAIKResponseB>Z<github.com/openbao/openbao/deviceattestpoc/proto;certserviceb\x06proto3"

var (
	file_proto_certservice_proto_rawDescOnce sync.Once
	file_proto_certservice_proto_rawDescData []byte
)

func file_proto_certservice_proto_rawDescGZIP() []byte {
	file_proto_certservice_proto_rawDescOnce.Do(func() {
		file_proto_certservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_certservice_proto_rawDesc), len(file_proto_certservice_proto_rawDesc)))
	})
	return file_proto_certservice_proto_rawDescData
}

var file_proto_certservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_certservice_proto_goTypes = []any{
	(*CertRequest)(nil),          // 0: certservice.CertRequest
	(*AttestationSubmit)(nil),    // 1: certservice.AttestationSubmit
	(*GetCertRequest)(nil),       // 2: certservice.GetCertRequest
	(*CertResponse)(nil),         // 3: certservice.CertResponse
	(*TPMEnrollmentRequest)(nil), // 4: certservice.TPMEnrollmentRequest
	(*EnrollmentResponse)(nil),   // 5: certservice.EnrollmentResponse
	(*ProvisionAIKRequest)(nil),  // 6: certservice.ProvisionAIKRequest
	(*ProvisionAIKResponse)(nil), // 7: certservice.ProvisionAIKResponse
}
var file_proto_certservice_proto_depIdxs = []int32{
	0, // 0: certservice.CertificateService.RequestCertificate:input_type -> certservice.CertRequest
	1, // 1: certservice.CertificateService.SubmitAttestation:input_type -> certservice.AttestationSubmit
	2, // 2: certservice.CertificateService.GetCertificate:input_type -> certservice.GetCertRequest
	4, // 3: certservice.CertificateService.EnrollTPM:input_type -> certservice.TPMEnrollmentRequest
	6, // 4: certservice.CertificateService.ProvisionAIK:input_type -> certservice.ProvisionAIKRequest
	3, // 5: certservice.CertificateService.RequestCertificate:output_type -> certservice.CertResponse
	3, // 6: certservice.CertificateService.SubmitAttestation:output_type -> certservice.CertResponse
	3, // 7: certservice.CertificateService.GetCertificate:output_type -> certservice.CertResponse
	5, // 8: certservice.CertificateService.EnrollTPM:output_type -> certservice.EnrollmentResponse
	7, // 9: certservice.CertificateService.ProvisionAIK:output_type -> certservice.ProvisionAIKResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_certservice_proto_init() }
func file_proto_certservice_proto_init() {
	if File_proto_certservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_certservice_proto_rawDesc), len(file_proto_certservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_certservice_proto_goTypes,
		DependencyIndexes: file_proto_certservice_proto_depIdxs,
		MessageInfos:      file_proto_certservice_proto_msgTypes,
	}.Build()
	File_proto_certservice_proto = out.File
	file_proto_certservice_proto_goTypes = nil
	file_proto_certservice_proto_depIdxs = nil
}
