// Copyright (c) OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/certservice.proto

package certservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertificateService_RequestCertificate_FullMethodName = "/certservice.CertificateService/RequestCertificate"
	CertificateService_SubmitAttestation_FullMethodName  = "/certservice.CertificateService/SubmitAttestation"
	CertificateService_FinalizeOrder_FullMethodName      = "/certservice.CertificateService/FinalizeOrder"
	CertificateService_GetCertificate_FullMethodName     = "/certservice.CertificateService/GetCertificate"
	CertificateService_EnrollTPM_FullMethodName          = "/certservice.CertificateService/EnrollTPM"
	CertificateService_ProvisionLAK_FullMethodName       = "/certservice.CertificateService/ProvisionLAK"
	CertificateService_ActivateCredential_FullMethodName = "/certservice.CertificateService/ActivateCredential"
)

// CertificateServiceClient is the client API for CertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateServiceClient interface {
	RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error)
	FinalizeOrder(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*CertResponse, error)
	GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error)
	EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	ProvisionLAK(ctx context.Context, in *ProvisionLAKRequest, opts ...grpc.CallOption) (*ProvisionLAKResponse, error)
	ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error)
}

type certificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateServiceClient(cc grpc.ClientConnInterface) CertificateServiceClient {
	return &certificateServiceClient{cc}
}

func (c *certificateServiceClient) RequestCertificate(ctx context.Context, in *CertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_RequestCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) SubmitAttestation(ctx context.Context, in *AttestationSubmit, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_SubmitAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) FinalizeOrder(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_FinalizeOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) GetCertificate(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*CertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertResponse)
	err := c.cc.Invoke(ctx, CertificateService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) EnrollTPM(ctx context.Context, in *TPMEnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, CertificateService_EnrollTPM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) ProvisionLAK(ctx context.Context, in *ProvisionLAKRequest, opts ...grpc.CallOption) (*ProvisionLAKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionLAKResponse)
	err := c.cc.Invoke(ctx, CertificateService_ProvisionLAK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateServiceClient) ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateCredentialResponse)
	err := c.cc.Invoke(ctx, CertificateService_ActivateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateServiceServer is the server API for CertificateService service.
// All implementations must embed UnimplementedCertificateServiceServer
// for forward compatibility.
type CertificateServiceServer interface {
	RequestCertificate(context.Context, *CertRequest) (*CertResponse, error)
	SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error)
	FinalizeOrder(context.Context, *FinalizeRequest) (*CertResponse, error)
	GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error)
	EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error)
	ProvisionLAK(context.Context, *ProvisionLAKRequest) (*ProvisionLAKResponse, error)
	ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error)
	mustEmbedUnimplementedCertificateServiceServer()
}

// UnimplementedCertificateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificateServiceServer struct{}

func (UnimplementedCertificateServiceServer) RequestCertificate(context.Context, *CertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) SubmitAttestation(context.Context, *AttestationSubmit) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAttestation not implemented")
}
func (UnimplementedCertificateServiceServer) FinalizeOrder(context.Context, *FinalizeRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeOrder not implemented")
}
func (UnimplementedCertificateServiceServer) GetCertificate(context.Context, *GetCertRequest) (*CertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedCertificateServiceServer) EnrollTPM(context.Context, *TPMEnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrollTPM not implemented")
}
func (UnimplementedCertificateServiceServer) ProvisionLAK(context.Context, *ProvisionLAKRequest) (*ProvisionLAKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionLAK not implemented")
}
func (UnimplementedCertificateServiceServer) ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateCredential not implemented")
}
func (UnimplementedCertificateServiceServer) mustEmbedUnimplementedCertificateServiceServer() {}
func (UnimplementedCertificateServiceServer) testEmbeddedByValue()                            {}

// UnsafeCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateServiceServer will
// result in compilation errors.
type UnsafeCertificateServiceServer interface {
	mustEmbedUnimplementedCertificateServiceServer()
}

func RegisterCertificateServiceServer(s grpc.ServiceRegistrar, srv CertificateServiceServer) {
	// If the following call pancis, it indicates UnimplementedCertificateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertificateService_ServiceDesc, srv)
}

func _CertificateService_RequestCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_RequestCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).RequestCertificate(ctx, req.(*CertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_SubmitAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_SubmitAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).SubmitAttestation(ctx, req.(*AttestationSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_FinalizeOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).FinalizeOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_FinalizeOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).FinalizeOrder(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).GetCertificate(ctx, req.(*GetCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_EnrollTPM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TPMEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_EnrollTPM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).EnrollTPM(ctx, req.(*TPMEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_ProvisionLAK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionLAKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).ProvisionLAK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_ProvisionLAK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).ProvisionLAK(ctx, req.(*ProvisionLAKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateService_ActivateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateServiceServer).ActivateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateService_ActivateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateServiceServer).ActivateCredential(ctx, req.(*ActivateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateService_ServiceDesc is the grpc.ServiceDesc for CertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "certservice.CertificateService",
	HandlerType: (*CertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCertificate",
			Handler:    _CertificateService_RequestCertificate_Handler,
		},
		{
			MethodName: "SubmitAttestation",
			Handler:    _CertificateService_SubmitAttestation_Handler,
		},
		{
			MethodName: "FinalizeOrder",
			Handler:    _CertificateService_FinalizeOrder_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _CertificateService_GetCertificate_Handler,
		},
		{
			MethodName: "EnrollTPM",
			Handler:    _CertificateService_EnrollTPM_Handler,
		},
		{
			MethodName: "ProvisionLAK",
			Handler:    _CertificateService_ProvisionLAK_Handler,
		},
		{
			MethodName: "ActivateCredential",
			Handler:    _CertificateService_ActivateCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certservice.proto",
}
